// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZV7bvg9lOeaVtnFX_Wpe_v53PG9BKh5E',
    appId: '1:87033406861:android:e2f4e63facbde6342109c4',
    messagingSenderId: '87033406861',
    projectId: 'flutter-labelscan',
    storageBucket: 'flutter-labelscan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6s7284ZgSzAlgjPOsXyECfZ_7po4HEkw',
    appId: '1:87033406861:ios:f2533e639ed917ce2109c4',
    messagingSenderId: '87033406861',
    projectId: 'flutter-labelscan',
    storageBucket: 'flutter-labelscan.firebasestorage.app',
    androidClientId: '87033406861-sa2ek1q838ktgrm1g7skst8mg5evtdoe.apps.googleusercontent.com',
    iosClientId: '87033406861-v2lmc96enii8l31b9a2tkaehncl96bph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabelscan',
  );
}
